<x-public-layout>
    <div class="py-6 min-h-screen">
        <div class="sm:px-6 mx-2 lg:px-8 ">
            <div class="shadow sm:rounded-md sm:overflow-hidden">
                <div class="px-4 py-5 bg-white space-y-6">

                    {{-- Title Form --}}
                    <div>
                        <h1 class="block"> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Volutpat maecenas volutpat blandit aliquam. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Hendrerit gravida rutrum quisque non tellus orci. Habitant morbi tristique senectus et netus et malesuada. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Mi proin sed libero enim sed faucibus. Viverra tellus in hac habitasse. Est placerat in egestas erat imperdiet sed euismod nisi. Quam lacus suspendisse faucibus interdum posuere. Velit dignissim sodales ut eu sem integer. Cursus mattis molestie a iaculis at erat. Sed sed risus pretium quam. Non sodales neque sodales ut etiam sit amet nisl. Tortor pretium viverra suspendisse potenti nullam ac.

                            Metus dictum at tempor commodo. Integer eget aliquet nibh praesent tristique. Hendrerit gravida rutrum quisque non. Diam maecenas sed enim ut sem viverra. Sit amet aliquam id diam. Penatibus et magnis dis parturient montes nascetur. Aenean euismod elementum nisi quis. Lacinia at quis risus sed. Blandit massa enim nec dui nunc mattis enim. Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Penatibus et magnis dis parturient montes nascetur ridiculus. Vitae congue eu consequat ac felis donec et. Posuere urna nec tincidunt praesent semper feugiat nibh. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. Dignissim sodales ut eu sem. Volutpat est velit egestas dui id ornare. Auctor eu augue ut lectus arcu bibendum at. Turpis tincidunt id aliquet risus feugiat in ante metus dictum. Et malesuada fames ac turpis egestas maecenas.

                            Sit amet justo donec enim diam. Quisque egestas diam in arcu cursus euismod quis viverra. Condimentum vitae sapien pellentesque habitant. Suscipit tellus mauris a diam maecenas sed enim ut sem. Proin fermentum leo vel orci porta non pulvinar. Purus in massa tempor nec feugiat nisl pretium. Tellus rutrum tellus pellentesque eu tincidunt. A pellentesque sit amet porttitor eget dolor morbi. Felis eget velit aliquet sagittis id consectetur purus. Vitae purus faucibus ornare suspendisse sed nisi lacus. Nulla aliquet porttitor lacus luctus. Elit ullamcorper dignissim cras tincidunt lobortis. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim.

                            Leo in vitae turpis massa sed elementum. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Pretium nibh ipsum consequat nisl vel. Amet luctus venenatis lectus magna. Sed vulputate mi sit amet mauris commodo quis. Vitae purus faucibus ornare suspendisse sed. Tristique senectus et netus et malesuada. Tincidunt arcu non sodales neque sodales ut etiam sit amet. Malesuada fames ac turpis egestas. Eu non diam phasellus vestibulum. Ipsum dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. Varius sit amet mattis vulputate enim nulla. Pretium nibh ipsum consequat nisl vel. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Duis tristique sollicitudin nibh sit. Laoreet suspendisse interdum consectetur libero id faucibus. Dui id ornare arcu odio ut sem nulla. Facilisi etiam dignissim diam quis enim. Velit scelerisque in dictum non. Risus in hendrerit gravida rutrum quisque non tellus orci ac.

                            Justo eget magna fermentum iaculis eu non. Proin fermentum leo vel orci porta non pulvinar neque laoreet. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Scelerisque in dictum non consectetur. Justo donec enim diam vulputate. Mattis rhoncus urna neque viverra justo nec ultrices dui. Sit amet commodo nulla facilisi nullam vehicula ipsum. Feugiat nibh sed pulvinar proin gravida. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Non diam phasellus vestibulum lorem sed risus ultricies. Magna sit amet purus gravida quis blandit turpis cursus. Odio aenean sed adipiscing diam donec. Ac auctor augue mauris augue neque gravida in fermentum et. Integer vitae justo eget magna fermentum iaculis eu non.

                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Volutpat maecenas volutpat blandit aliquam. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Hendrerit gravida rutrum quisque non tellus orci. Habitant morbi tristique senectus et netus et malesuada. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Mi proin sed libero enim sed faucibus. Viverra tellus in hac habitasse. Est placerat in egestas erat imperdiet sed euismod nisi. Quam lacus suspendisse faucibus interdum posuere. Velit dignissim sodales ut eu sem integer. Cursus mattis molestie a iaculis at erat. Sed sed risus pretium quam. Non sodales neque sodales ut etiam sit amet nisl. Tortor pretium viverra suspendisse potenti nullam ac.

                            Metus dictum at tempor commodo. Integer eget aliquet nibh praesent tristique. Hendrerit gravida rutrum quisque non. Diam maecenas sed enim ut sem viverra. Sit amet aliquam id diam. Penatibus et magnis dis parturient montes nascetur. Aenean euismod elementum nisi quis. Lacinia at quis risus sed. Blandit massa enim nec dui nunc mattis enim. Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Penatibus et magnis dis parturient montes nascetur ridiculus. Vitae congue eu consequat ac felis donec et. Posuere urna nec tincidunt praesent semper feugiat nibh. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. Dignissim sodales ut eu sem. Volutpat est velit egestas dui id ornare. Auctor eu augue ut lectus arcu bibendum at. Turpis tincidunt id aliquet risus feugiat in ante metus dictum. Et malesuada fames ac turpis egestas maecenas.

                            Sit amet justo donec enim diam. Quisque egestas diam in arcu cursus euismod quis viverra. Condimentum vitae sapien pellentesque habitant. Suscipit tellus mauris a diam maecenas sed enim ut sem. Proin fermentum leo vel orci porta non pulvinar. Purus in massa tempor nec feugiat nisl pretium. Tellus rutrum tellus pellentesque eu tincidunt. A pellentesque sit amet porttitor eget dolor morbi. Felis eget velit aliquet sagittis id consectetur purus. Vitae purus faucibus ornare suspendisse sed nisi lacus. Nulla aliquet porttitor lacus luctus. Elit ullamcorper dignissim cras tincidunt lobortis. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim.

                            Leo in vitae turpis massa sed elementum. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Pretium nibh ipsum consequat nisl vel. Amet luctus venenatis lectus magna. Sed vulputate mi sit amet mauris commodo quis. Vitae purus faucibus ornare suspendisse sed. Tristique senectus et netus et malesuada. Tincidunt arcu non sodales neque sodales ut etiam sit amet. Malesuada fames ac turpis egestas. Eu non diam phasellus vestibulum. Ipsum dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. Varius sit amet mattis vulputate enim nulla. Pretium nibh ipsum consequat nisl vel. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Duis tristique sollicitudin nibh sit. Laoreet suspendisse interdum consectetur libero id faucibus. Dui id ornare arcu odio ut sem nulla. Facilisi etiam dignissim diam quis enim. Velit scelerisque in dictum non. Risus in hendrerit gravida rutrum quisque non tellus orci ac.

                            Justo eget magna fermentum iaculis eu non. Proin fermentum leo vel orci porta non pulvinar neque laoreet. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Scelerisque in dictum non consectetur. Justo donec enim diam vulputate. Mattis rhoncus urna neque viverra justo nec ultrices dui. Sit amet commodo nulla facilisi nullam vehicula ipsum. Feugiat nibh sed pulvinar proin gravida. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Non diam phasellus vestibulum lorem sed risus ultricies. Magna sit amet purus gravida quis blandit turpis cursus. Odio aenean sed adipiscing diam donec. Ac auctor augue mauris augue neque gravida in fermentum et. Integer vitae justo eget magna fermentum iaculis eu non.

                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Volutpat maecenas volutpat blandit aliquam. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Hendrerit gravida rutrum quisque non tellus orci. Habitant morbi tristique senectus et netus et malesuada. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Mi proin sed libero enim sed faucibus. Viverra tellus in hac habitasse. Est placerat in egestas erat imperdiet sed euismod nisi. Quam lacus suspendisse faucibus interdum posuere. Velit dignissim sodales ut eu sem integer. Cursus mattis molestie a iaculis at erat. Sed sed risus pretium quam. Non sodales neque sodales ut etiam sit amet nisl. Tortor pretium viverra suspendisse potenti nullam ac.

                            Metus dictum at tempor commodo. Integer eget aliquet nibh praesent tristique. Hendrerit gravida rutrum quisque non. Diam maecenas sed enim ut sem viverra. Sit amet aliquam id diam. Penatibus et magnis dis parturient montes nascetur. Aenean euismod elementum nisi quis. Lacinia at quis risus sed. Blandit massa enim nec dui nunc mattis enim. Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Penatibus et magnis dis parturient montes nascetur ridiculus. Vitae congue eu consequat ac felis donec et. Posuere urna nec tincidunt praesent semper feugiat nibh. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. Dignissim sodales ut eu sem. Volutpat est velit egestas dui id ornare. Auctor eu augue ut lectus arcu bibendum at. Turpis tincidunt id aliquet risus feugiat in ante metus dictum. Et malesuada fames ac turpis egestas maecenas.

                            Sit amet justo donec enim diam. Quisque egestas diam in arcu cursus euismod quis viverra. Condimentum vitae sapien pellentesque habitant. Suscipit tellus mauris a diam maecenas sed enim ut sem. Proin fermentum leo vel orci porta non pulvinar. Purus in massa tempor nec feugiat nisl pretium. Tellus rutrum tellus pellentesque eu tincidunt. A pellentesque sit amet porttitor eget dolor morbi. Felis eget velit aliquet sagittis id consectetur purus. Vitae purus faucibus ornare suspendisse sed nisi lacus. Nulla aliquet porttitor lacus luctus. Elit ullamcorper dignissim cras tincidunt lobortis. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim.

                            Leo in vitae turpis massa sed elementum. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Pretium nibh ipsum consequat nisl vel. Amet luctus venenatis lectus magna. Sed vulputate mi sit amet mauris commodo quis. Vitae purus faucibus ornare suspendisse sed. Tristique senectus et netus et malesuada. Tincidunt arcu non sodales neque sodales ut etiam sit amet. Malesuada fames ac turpis egestas. Eu non diam phasellus vestibulum. Ipsum dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. Varius sit amet mattis vulputate enim nulla. Pretium nibh ipsum consequat nisl vel. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Duis tristique sollicitudin nibh sit. Laoreet suspendisse interdum consectetur libero id faucibus. Dui id ornare arcu odio ut sem nulla. Facilisi etiam dignissim diam quis enim. Velit scelerisque in dictum non. Risus in hendrerit gravida rutrum quisque non tellus orci ac.

                            Justo eget magna fermentum iaculis eu non. Proin fermentum leo vel orci porta non pulvinar neque laoreet. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Scelerisque in dictum non consectetur. Justo donec enim diam vulputate. Mattis rhoncus urna neque viverra justo nec ultrices dui. Sit amet commodo nulla facilisi nullam vehicula ipsum. Feugiat nibh sed pulvinar proin gravida. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Non diam phasellus vestibulum lorem sed risus ultricies. Magna sit amet purus gravida quis blandit turpis cursus. Odio aenean sed adipiscing diam donec. Ac auctor augue mauris augue neque gravida in fermentum et. Integer vitae justo eget magna fermentum iaculis eu non.</h1>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <x-slot name="scripts">
        <script type="text/javascript">


        </script>
    </x-slot>

</x-public-layout>
